package sv.edu.udb.www.entities;
// Generated 10-24-2019 06:58:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.NotBlank;

/**
 * Editoriales generated by hbm2java
 */
@Entity
@Table(name="editoriales"
    ,catalog="inventario_libros"
)
public class Editoriales  implements java.io.Serializable {

    @NotBlank(message = "El codigo de editorial es requerido")
    @Pattern( regexp = "EDI[0-9]{3}")
     private String codigoEditorial;
    @NotBlank()
     private String nombreEditorial;
    @NotBlank(message = "El contacto es requerido")
     private String contacto;
    @NotBlank(message = "El telefono es requerido")
    @Pattern(regexp = "[267][0-9]{3}-[0-9]{4}", message = "El telefono no tiene el formato correcto")
     private String telefono;
     private Set<Libros> libroses = new HashSet<Libros>(0);

    public Editoriales() {
    }

	
    public Editoriales(String codigoEditorial, String nombreEditorial, String contacto, String telefono) {
        this.codigoEditorial = codigoEditorial;
        this.nombreEditorial = nombreEditorial;
        this.contacto = contacto;
        this.telefono = telefono;
    }
    public Editoriales(String codigoEditorial, String nombreEditorial, String contacto, String telefono, Set<Libros> libroses) {
       this.codigoEditorial = codigoEditorial;
       this.nombreEditorial = nombreEditorial;
       this.contacto = contacto;
       this.telefono = telefono;
       this.libroses = libroses;
    }
   
     @Id 

    
    @Column(name="codigo_editorial", unique=true, nullable=false, length=6)
    public String getCodigoEditorial() {
        return this.codigoEditorial;
    }
    
    public void setCodigoEditorial(String codigoEditorial) {
        this.codigoEditorial = codigoEditorial;
    }

    
    @Column(name="nombre_editorial", nullable=false, length=30)
    public String getNombreEditorial() {
        return this.nombreEditorial;
    }
    
    public void setNombreEditorial(String nombreEditorial) {
        this.nombreEditorial = nombreEditorial;
    }

    
    @Column(name="contacto", nullable=false, length=30)
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }

    
    @Column(name="telefono", nullable=false, length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="editoriales")
    public Set<Libros> getLibroses() {
        return this.libroses;
    }
    
    public void setLibroses(Set<Libros> libroses) {
        this.libroses = libroses;
    }




}


